# Generated by Django 5.0.1 on 2024-01-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_flashcardchallenge_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
